urls:
  home:
    rails: "https://www.railstutorial.org/"
  about:
    learn_enough: "https://www.learnenough.com/"
    book: "https://www.railstutorial.org/book"
    series: "https://screencasts.railstutorial.org/"
    ruby: "https://rubyonrails.org/"
  contact:
    contact: "https://www.railstutorial.org/contact"
  help:
    help: "https://www.railstutorial.org/help"
    book: "https://www.railstutorial.org/book"
  footer:
    author: "https://www.michaelhartl.com/"
    news: "https://news.railstutorial.org/"
numbers:
  name_max_length: 50
  VALID_EMAIL_REGEX: \A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z
  email_max_length: 250
  password_min_length: 6
user_helper:
  size: 80
gravatar:
  email: "https://gravatar.com/emails"
  size: 50
